package com.example.seniorshield.domain.model

enum class RiskSignal {
    UNKNOWN_CALLER,
    LONG_CALL_DURATION,
    UNVERIFIED_CALLER,
    REMOTE_CONTROL_APP_OPENED,
    BANKING_APP_OPENED_AFTER_REMOTE_APP,
    HIGH_RISK_DEVICE_ENVIRONMENT,
    SUSPICIOUS_APP_INSTALLED,
    REPEATED_UNKNOWN_CALLER,
    REPEATED_CALL_THEN_LONG_TALK,
    TELEBANKING_AFTER_SUSPICIOUS,
}